version: '3.8'

services:

  ollama:
    build: ollama
    ports:
      - "11434:11434"
    environment:
      - MY_OLLAMA_MODELS=llama3,deepseek-coder:1.3b,codellama
      - OLLAMA_HOST=0.0.0.0
      - OLLAMA_NUM_PARALLEL=1
    healthcheck:
      test: curl --fail http://localhost:11434/ || exit 1
      interval: 60s
      timeout: 5s
      retries: 3
      start_period: 5s
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all # alternatively, use `count: all` for all GPUs
              capabilities: [ gpu ]
    volumes:
      - ./ollama/llm/:/root/.ollama/models/
